return {
  name = "clipboard-server",
  version = "0.0.1",
  luvi = {
    version = "2.12.0",
    flavor = "regular",
  },
  license = "MIT",
  homepage = "https://github.com/q962/clipboared-server",
  description = " 将个人电脑上的剪切板数据共享给局域网设备。主要给手机使用。",
  tags = { "luvit", "meta" },
  author = { name = "q962" },
  contributors = {
  },
  dependencies = {
    -- "luvit/buffer@2.0.0",
    -- "luvit/childprocess@2.1.2",
    -- "luvit/codec@2.0.0",
    -- "luvit/core@2.0.3",
    -- "luvit/dgram@2.0.0",
    -- "luvit/dns@2.0.3",
    -- "luvit/fs@2.0.1",
    -- "luvit/helpful@2.0.1",
    -- "luvit/hooks@2.0.0",
    -- "luvit/http@2.1.4",
    -- "luvit/http-codec@2.0.3",
    -- "luvit/http-header@1.0.0",
    -- "luvit/https@2.0.0",
    -- "luvit/json@2.5.1",
    -- "luvit/los@2.0.0",
    -- "luvit/net@2.0.3",
    -- "luvit/path@2.0.1",
    -- "luvit/pretty-print@2.1.0",
    -- "luvit/process@2.1.2",
    -- "luvit/querystring@2.0.1",
    -- "luvit/readline@2.0.0",
    -- "luvit/repl@2.1.2",
    -- "luvit/require@2.2.2",
    -- "luvit/resource@2.0.0",
    -- "luvit/stream@2.0.2",
    -- "luvit/thread@2.0.0",
    -- "luvit/timer@2.0.1",
    -- "luvit/tls@2.3.0",
    -- "luvit/utils@2.0.0",
    -- "luvit/url@2.1.2",
    -- "luvit/ustring@2.0.0"
  },
  files = {
    "**.lua",
    "**.so",
    "**.dll",
    "!examples",
    "!tests",
    "!bench",
    "!lit-*",
  }
}
